### ISSUE TITLE
Use qbx_core lib instead of utils

### ISSUE THREAD

**Issue by nitrou5** [Qbox-project/qbx_jewelery#16]
### Summary

Use qbx_core lib instead of utils

### Reproduction

1. Launch resource
2. Deprecation warning of qbx_core utils shows in console

### Expected behavior

No deprecation warnings

### Actual behavior

Deprecation warning of qbx_core utils shows in console

### Current Version

v1.0.0

### Custom Resources

n/a

**Comment by solareon** [comment]
Closed via #17
